version: '3.7'

services:

  groundup-web:
    container_name: groundup-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      # - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true